# Generated by Django 5.0.9 on 2024-11-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo1',
            field=models.BinaryField(blank=True, max_length='max', null=True),
        ),
    ]
