# Generated by Django 5.0.9 on 2024-11-18 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_photo1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo1',
        ),
    ]
