# Generated by Django 5.1.3 on 2024-11-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_photo1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
