# Generated by Django 5.0.9 on 2024-11-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
